[package]
name = "sherpa-cli"
version = "1.0.0-beta1"
edition = "2021"

[[bin]]
name = "sherpa"
path = "./main.rs"

[dependencies]
clap = { version="4.0.29" }

[dependencies.sherpa]
path = "../../lib/sherpa"


