image: rustlang/rust:nightly

stages:
  - test
  - build

test_sherpa_packages:
  stage: test

  rules:
    - when: always

  script:
    - cargor

build_sherpa_packages:
  stage: build

  rules:
    - when: always

  script:
    - echo "Hello World"
