image: $CI_REGISTRY/anthony/sherpa/sherpa-build:latest

variables:
  GIT_DEPTH: 10

stages:
  - build
  - test
  - build-site
  - deploy

build_core:
  stage: build
  image: $CI_REGISTRY/anthony/sherpa/sherpa-build:latest
  rules:
    - when: always
  script:
    - ./scripts/bootstrap_binary
  artifacts:
    untracked: false
    when: on_success
    expire_in: "7 days"
    paths:
      - "src/lib/sherpa-core/lib/"
      - "src/lib/sherpa-core/grammar/compile/parser/sherpa.rs"

build_wasm:
  stage: build
  image: $CI_REGISTRY/anthony/sherpa/sherpa-build:latest
  rules:
    - when: always
  script:
    - "curl https://rustwasm.github.io/wasm-pack/installer/init.sh -sSf | sh"
    - ./scripts/build_wasm
  artifacts:
    untracked: false
    when: on_success
    expire_in: "7 days"
    paths:
      - "src/web/sherpa-wasm/pkg"

build_site_node:
  stage: build-site
  image: node:19-slim
  needs: []
  rules:
    - when: always
  script:
    - cd ./src/web/doc
    - npm install
  artifacts:
    untracked: false
    when: on_success
    expire_in: "15 min"
    paths:
      - "src/web/doc/node_modules"

build_site_hugo:
  stage: build-site
  image: klakegg/hugo:0.107.0-ext-alpine-ci
  needs:
    - build_site_node
    - build_wasm
  rules:
    - when: on_success
  script:
    - mkdir -p ./src/web/doc/assets/js/sherpa
    - mkdir -p ./src/web/doc/static/js/lab
    - cp ./src/web/sherpa-wasm/pkg/* ./src/web/doc/assets/js/sherpa
    - mv ./src/web/doc/assets/js/sherpa/sherpa_wasm_bg.wasm ./src/web/doc/static/js/lab
    - cd ./src/web/doc
    - hugo
  artifacts:
    untracked: false
    when: on_success
    expire_in: "7 days"
    paths:
      - "src/web/doc/public"

pages:
  stage: deploy
  image: alpine
  environment: production
  needs:
    - build_site_hugo
  rules:
    - when: on_success
  script:
    - mkdir public
    - cp -rf src/web/doc/public/* ./public
  artifacts:
    paths:
      - public

test_sherpa:
  stage: test
  image: $CI_REGISTRY/anthony/sherpa/sherpa-build:latest
  needs:
    - "build_core"
  rules:
    - when: on_success
  script:
    - ./scripts/run_tests
