image: $CI_REGISTRY/anthony/sherpa/sherpa-build:latest

stages:
  - test
  - build

test_sherpa_packages:
  stage: test

  rules:
    - when: always

  script:
    - ./scripts/bootstrap_binary
    - ./scripts/run_tests

build_sherpa_packages:
  stage: build

  rules:
    - when: always

  script:
    - echo "Hello World"
