image: sherpa-build

stages:
  - test
  - build

test_sherpa_packages:
  stage: test

  rules:
    - when: always

  script:
    - cargo test --workspace

build_sherpa_packages:
  stage: build

  rules:
    - when: always

  script:
    - echo "Hello World"
