[workspace]

members = [
    "source/lib/hctk",
    "source/app/compile",
    "test/e2e/basic_grammar",
    "test/e2e/basic_grammar_llvm",
    "test/e2e/basic_language_llvm"
]

[profile.dev]
debug = 2

[profile.release]
opt-level=3
debug = 0