# Line Widths
max_width = 80
array_width = 70
fn_call_width = 70
comment_width = 70
enum_discrim_align_threshold = 50
struct_field_align_threshold = 50
newline_style = "Unix"
tab_spaces = 4

hide_parse_errors = true

binop_separator = "Front"

blank_lines_lower_bound = 0
blank_lines_upper_bound = 1

brace_style = "AlwaysNextLine"

# Comments
#format_code_in_doc_comments = true
wrap_comments = true
normalize_comments = true

condense_wildcard_suffixes = true
hex_literal_case = "Upper"
merge_derives = true

imports_granularity = "Item"

imports_layout = "HorizontalVertical"

overflow_delimited_expr = true

reorder_impl_items = true

report_todo = "Always"
