[package]
name = "sherpa-cli"
version = "1.0.0-beta1"
edition = "2021"

[[bin]]
name = "sherpa"
path = "./main.rs"

[dependencies]
clap = { version="4.0.29" }

[dependencies.sherpa_core]
path = "../../lib/sherpa-core"

[profile.release]
opt-level=3
panic = 'abort'
lto = true
debug = 0