[package]
name = "radlr_rust_runtime"
version = "1.0.1-beta1"
edition = "2021"

[lib]
path = "./lib.rs"

[features]
wasm-lab = ["wasm-bindgen"]

[dependencies.wasm-bindgen]
optional = true
version = "0.2.87"