image: $CI_REGISTRY/anthony/radlr/radlr-build:latest

variables:
  GIT_DEPTH: 10

stages:
  - build
  - test
  - build-site
  - deploy

build_core:
  stage: build
  image: $CI_REGISTRY/anthony/radlr/radlr-build:latest
  rules:
    - when: always
  script:
    - ./scripts/bootstrap_binary
  artifacts:
    untracked: false
    when: on_success
    expire_in: "7 days"
    paths:
      - "crates/radlr-core/lib/"
      - "crates/radlr-core/grammar/compile/parser/radlr.rs"

build_wasm:
  stage: build
  image: $CI_REGISTRY/anthony/radlr/radlr-build:latest
  rules:
    - when: always
  script:
    - "curl https://rustwasm.github.io/wasm-pack/installer/init.sh -sSf | sh"
    - ./scripts/build_wasm
  artifacts:
    untracked: false
    when: on_success
    expire_in: "7 days"
    paths:
      - "web/radlr-wasm/pkg"

build_site_node:
  stage: build-site
  image: node:19-slim
  needs: []
  rules:
    - when: always
  script:
    - cd ./web/doc
    - npm install
  artifacts:
    untracked: false
    when: on_success
    expire_in: "15 min"
    paths:
      - "web/doc/node_modules"

build_site_hugo:
  stage: build-site
  image: $CI_REGISTRY/anthony/radlr/hugo-build:latest
  needs:
    - build_site_node
    - build_wasm
  rules:
    - when: on_success
  script:
    - mkdir -p ./web/doc/assets/js/radlr
    - mkdir -p ./web/doc/static/js/lab
    - cp ./web/radlr-wasm/pkg/* ./web/doc/assets/js/radlr
    - mv ./web/doc/assets/js/radlr/radlr_wasm_bg.wasm ./web/doc/static/js/lab
    - cd ./web/doc
    - hugo -b $CI_PAGES_URL
  artifacts:
    untracked: false
    when: on_success
    expire_in: "7 days"
    paths:
      - "web/doc/public"

pages:
  stage: deploy
  image: alpine
  environment: production
  needs:
    - build_site_hugo
  rules:
    - when: on_success
  script:
    - mkdir public
    - cp -rf web/doc/public/* ./public
  artifacts:
    paths:
      - public

test_radlr_binary_parser:
  stage: test
  image: $CI_REGISTRY/anthony/radlr/radlr-build:latest
  needs:
    - "build_core"
  rules:
    - when: on_success
  script:
    - ./scripts/run_binary_tests

test_radlr_bytecode_parser:
  stage: test
  image: $CI_REGISTRY/anthony/radlr/radlr-build:latest
  needs:
    - "build_core"
  rules:
    - when: on_success
  script:
    - ./scripts/run_bytecode_tests
